####################################################################
#                                                                  #
#                    EVERYTHING MADE BY ZPLEUM                     #
#                                                                  #
####################################################################

# กำหนดค่าต่างๆ สำหรับการรวบรวมข้อมูล
collection:
  enabled: true         # เปิด/ปิดการรวบรวมข้อมูล
  interval: 60          # ความถี่ในการรวบรวมข้อมูล (นาที)
  maxRandomPlayers: 5   # จำนวนผู้เล่นแบบสุ่มที่จะวิเคราะห์
  timezone: "Asia/Bangkok" # Timezone สำหรับข้อความเวลา

# การตั้งค่าข้อความสำหรับ DiscordSRV
discord:
  enabled: true               # เปิด/ปิดการส่งข้อความไปยัง Discord
  useBroadcastCommand: true   # ใช้คำสั่ง broadcast แทนการส่งข้อความโดยตรง
  summaryMessageFormat: |
    
    🔥 __รายงานสรุปสถิติผู้เล่น ประจำวันที่__ 📃 **{date}** :
    
    - ✅ ผู้เล่นทั้งหมด : **{totalPlayers}** คน
    - ✅ เวลาเล่นเฉลี่ย : **{averagePlayTime}** นาที
    - ✅ คำสั่งที่ใช้ทั้งหมด : **{totalCommandsUsed}** ครั้ง
    - ✅ จำนวนพืชที่เก็บเกี่ยวทั้งหมด : **{totalCropsHarvested}** ต้น
  detailedMessageFormat: |
    
    -------------------------------------------------------------------------------------
    
    🎁 __รายงานการวิเคราะห์ผู้เล่น ประจำวันที่__ 📃 **{date}** ( สุ่มจำนวน 5 คน ) :
    
     {detailedPlayerStats}
    
    - Found Some Error? [Contact Me Now !!](https://pleum.mc-zero.net/)
    - System Made By zPleum [Contact Me !](https://pleum.mc-zero.net/)

# การตั้งค่าคำสั่งและการรีโหลด
commands:
  reload: true  # เปิดให้ใช้คำสั่ง /zdatagetter reload

####################################################################
#                                                                  #
#                    EVERYTHING MADE BY ZPLEUM                     #
#                                                                  #
####################################################################
